-- ==============================================================================
-- Silence External 266 · Supabase Postgres Schema & Policies (Idempotent)
-- ==============================================================================

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. ENUMS / TYPES (Безопасное создание без ошибок, если тип уже существует)
do $$ begin
    create type user_role as enum ('USER', 'ADMIN');
exception
    when duplicate_object then null;
end $$;

do $$ begin
    create type cheat_status as enum ('Undetected', 'Updating', 'Down');
exception
    when duplicate_object then null;
end $$;

do $$ begin
    create type roadmap_state as enum ('planned', 'in_progress', 'done');
exception
    when duplicate_object then null;
end $$;

-- 3. PROFILES TABLE
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    username text unique not null check (username ~ '^[a-zA-Z0-9_]{3,20}$'),
    email text,
    role user_role default 'USER'::user_role not null,
    banned boolean default false not null,
    avatar_url text,
    last_login_at timestamptz,
    created_at timestamptz default now() not null
);

-- 4. STATUS TABLE (Singleton / History)
create table if not exists public.status (
    id bigint generated by default as identity primary key,
    value cheat_status default 'Undetected'::cheat_status not null,
    comment text default 'Стабильная работа на текущей сборке devblog 266.' not null,
    game_version text default 'Rust Devblog 266' not null,
    ac_version text default 'Client/Server Integrity' not null,
    updated_at timestamptz default now() not null
);

-- 5. POSTS / CHANGELOG TABLE
create table if not exists public.posts (
    id uuid default gen_random_uuid() primary key,
    title text not null,
    slug text unique not null,
    version text default 'v266' not null,
    tags text[] default array['feature']::text[] not null,
    body text not null,
    cover_url text,
    published boolean default true not null,
    published_at timestamptz default now() not null,
    created_at timestamptz default now() not null
);

-- 6. FEATURES TABLE
create table if not exists public.features (
    id bigint generated by default as identity primary key,
    title text not null,
    category text default 'Visuals' not null,
    description text not null,
    icon_svg text not null,
    sort_order int default 0 not null,
    is_active boolean default true not null,
    created_at timestamptz default now() not null
);

-- 7. ROADMAP TABLE
create table if not exists public.roadmap (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    state roadmap_state default 'planned'::roadmap_state not null,
    sort_order int default 0 not null,
    created_at timestamptz default now() not null
);

-- 8. FAQ TABLE
create table if not exists public.faq (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    sort_order int default 0 not null,
    created_at timestamptz default now() not null
);

-- 9. AUDIT LOG TABLE
create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    actor text not null,
    action text not null,
    target text not null,
    payload jsonb,
    created_at timestamptz default now() not null
);

-- 10. SETTINGS TABLE
create table if not exists public.settings (
    key text primary key,
    value text not null,
    updated_at timestamptz default now() not null
);

-- ==============================================================================
-- RLS POLICIES
-- ==============================================================================
alter table public.profiles enable row level security;
alter table public.status enable row level security;
alter table public.posts enable row level security;
alter table public.features enable row level security;
alter table public.roadmap enable row level security;
alter table public.faq enable row level security;
alter table public.audit_log enable row level security;
alter table public.settings enable row level security;

-- HELPER FUNCTIONS FOR ROLES
create or replace function public.is_admin()
returns boolean security definer language sql stable as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'ADMIN'::user_role and banned = false
    );
$$;

-- PROFILES RLS
drop policy if exists "Read own profile or admin read all" on public.profiles;
create policy "Read own profile or admin read all" on public.profiles
    for select using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own non-sensitive profile" on public.profiles;
create policy "Users can update own non-sensitive profile" on public.profiles
    for update using (auth.uid() = id)
    with check (
        auth.uid() = id and 
        role = (select role from public.profiles where id = auth.uid()) and
        banned = (select banned from public.profiles where id = auth.uid())
    );

drop policy if exists "Admin full update profiles" on public.profiles;
create policy "Admin full update profiles" on public.profiles
    for update using (public.is_admin());

-- STATUS RLS
drop policy if exists "Public read status" on public.status;
create policy "Public read status" on public.status for select using (true);

drop policy if exists "Admin update status" on public.status;
create policy "Admin update status" on public.status for all using (public.is_admin());

-- POSTS RLS
drop policy if exists "Public read published posts" on public.posts;
create policy "Public read published posts" on public.posts for select using (published = true or public.is_admin());

drop policy if exists "Admin manage posts" on public.posts;
create policy "Admin manage posts" on public.posts for all using (public.is_admin());

-- FEATURES RLS
drop policy if exists "Public read features" on public.features;
create policy "Public read features" on public.features for select using (is_active = true or public.is_admin());

drop policy if exists "Admin manage features" on public.features;
create policy "Admin manage features" on public.features for all using (public.is_admin());

-- ROADMAP RLS
drop policy if exists "Public read roadmap" on public.roadmap;
create policy "Public read roadmap" on public.roadmap for select using (true);

drop policy if exists "Admin manage roadmap" on public.roadmap;
create policy "Admin manage roadmap" on public.roadmap for all using (public.is_admin());

-- FAQ RLS
drop policy if exists "Public read faq" on public.faq;
create policy "Public read faq" on public.faq for select using (true);

drop policy if exists "Admin manage faq" on public.faq;
create policy "Admin manage faq" on public.faq for all using (public.is_admin());

-- AUDIT LOG RLS
drop policy if exists "Admin read audit log" on public.audit_log;
create policy "Admin read audit log" on public.audit_log for select using (public.is_admin());

drop policy if exists "Server insert audit log" on public.audit_log;
create policy "Server insert audit log" on public.audit_log for insert with check (true);

-- SETTINGS RLS
drop policy if exists "Public read settings" on public.settings;
create policy "Public read settings" on public.settings for select using (true);

drop policy if exists "Admin manage settings" on public.settings;
create policy "Admin manage settings" on public.settings for all using (public.is_admin());

-- ==============================================================================
-- TRIGGERS
-- ==============================================================================

create or replace function public.handle_new_user()
returns trigger security definer language plpgsql as $$
declare
    _username text;
    _role user_role := 'USER'::user_role;
begin
    _username := coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1));
    if _username = 'flqshka' then
        _role := 'ADMIN'::user_role;
    end if;

    insert into public.profiles (id, username, email, role, avatar_url, created_at)
    values (
        new.id,
        _username,
        coalesce(new.raw_user_meta_data->>'real_email', new.email),
        _role,
        'https://api.dicebear.com/7.x/bottts/svg?seed=' || _username,
        now()
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

create or replace function public.audit_action_trigger()
returns trigger security definer language plpgsql as $$
declare
    _actor text := 'system';
    _user_id uuid := auth.uid();
begin
    if _user_id is not null then
        select username into _actor from public.profiles where id = _user_id;
        if _actor is null then
            _actor := _user_id::text;
        end if;
    end if;

    if tg_op = 'INSERT' then
        insert into public.audit_log (actor, action, target, payload)
        values (_actor, 'INSERT', tg_table_name, row_to_json(NEW));
    elsif tg_op = 'UPDATE' then
        insert into public.audit_log (actor, action, target, payload)
        values (_actor, 'UPDATE', tg_table_name, jsonb_build_object('old', row_to_json(OLD), 'new', row_to_json(NEW)));
    elsif tg_op = 'DELETE' then
        insert into public.audit_log (actor, action, target, payload)
        values (_actor, 'DELETE', tg_table_name, row_to_json(OLD));
    end if;
    return null;
end;
$$;

drop trigger if exists audit_posts on public.posts;
create trigger audit_posts after insert or update or delete on public.posts
for each row execute procedure public.audit_action_trigger();

drop trigger if exists audit_status on public.status;
create trigger audit_status after insert or update or delete on public.status
for each row execute procedure public.audit_action_trigger();

drop trigger if exists audit_features on public.features;
create trigger audit_features after insert or update or delete on public.features
for each row execute procedure public.audit_action_trigger();

drop trigger if exists audit_roadmap on public.roadmap;
create trigger audit_roadmap after insert or update or delete on public.roadmap
for each row execute procedure public.audit_action_trigger();

drop trigger if exists audit_faq on public.faq;
create trigger audit_faq after insert or update or delete on public.faq
for each row execute procedure public.audit_action_trigger();

drop trigger if exists audit_profiles on public.profiles;
create trigger audit_profiles after update on public.profiles
for each row execute procedure public.audit_action_trigger();

-- ==============================================================================
-- DEFAULT SEED DATA (ПОД DEVBLOG 266 + DRIVER)
-- ==============================================================================

insert into public.status (value, comment, game_version, ac_version)
values ('Undetected', 'Драйвер активен. Стабильная работа на сборках Rust Devblog 266.', 'Devblog 266', 'No AC / Server Side')
on conflict do nothing;

insert into public.features (title, category, description, icon_svg, sort_order)
values
('Player ESP & Skeleton', 'Visuals', 'Отображение игроков: боксы, 2D скелет, дистанция, активное оружие в руках, статус сна, полоса здоровья.', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>', 1),
('Aimbot & Prediction', 'Combat', 'Плавная наводка (Smooth), расчет баллистики и скорости пули под Devblog 266, выбор кости (Head/Chest/Pelvis).', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="22" y1="12" x2="18" y2="12"/><line x1="6" y1="12" x2="2" y2="12"/><line x1="12" y1="6" x2="12" y2="2"/><line x1="12" y1="22" x2="12" y2="18"/></svg>', 2),
('No Recoil & Spread', 'Weapons', 'Полный контроль отдачи и разброса оружия без модификации защищенной памяти игры.', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>', 3),
('Ore, Crates & World ESP', 'World', 'Руда (сера, металл, камень), ящики с лутом, сброшенные предметы, вертолет, турели и шкафы.', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/></svg>', 4),
('DirectX Overlay', 'Display', 'Внешний аппаратный оверлей с нулевым инпут-лагом и поддержкой любого разрешения экрана.', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>', 5),
('Kernel Driver RPM', 'Security', 'Чтение памяти через собственный режим ядра (Kernel Mode Driver). Отсутствие прямых дескрипторов к игре.', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>', 6)
on conflict do nothing;

insert into public.roadmap (title, description, state, sort_order)
values
('Драйверный стек чтения памяти', 'Стабильная реализация обмена данными между ядром и юзермод-клиентом.', 'done', 1),
('DirectX 11 ImGui оверлей', 'Аппаратный рендеринг визуалов с плавной синхронизацией фреймрейта.', 'done', 2),
('Баллистический предикшн под лук и огнестрел', 'Корректировка падения снарядов под физику сборки Devblog 266.', 'in_progress', 3),
('Фильтры лута и отображение шкафов', 'Кастомизация дистанции и фильтрации редких предметов.', 'planned', 4)
on conflict do nothing;

insert into public.faq (question, answer, sort_order)
values
('На каких версиях работает софт?', 'Оптимизировано под сборки Rust Devblog 266 (пиратские и no-AC сервера). Работает на Windows 10 и Windows 11 x64.', 1),
('Как работает софт?', 'Внешний клиент (External), который взаимодействует с игрой через kernel-mode драйвер и рисует визуальные элементы поверх окна игры.', 2),
('Как получить доступ к сборке 266?', 'Зарегистрируйте аккаунт, перейдите в личный кабинет и скачайте актуальный архив клиента.', 3)
on conflict do nothing;

insert into public.posts (title, slug, version, tags, body, published, published_at)
values
('Silence External 266: Релиз под Devblog', 'silence-external-266-release-devblog', 'v266.0', array['feature', 'driver'], '## Релиз Silence 266 под Devblog

Сборка адаптирована под сервера Rust Devblog 266:
- **Kernel Mode Driver**: Чтение структур памяти через драйвер без открытия юзермод хэндлов.
- **ESP & Skeleton**: Полный визуал игроков, дистанция и оружие.
- **No Recoil**: Контроль отдачи под классическую баллистику devblog 266.
- **Overlay**: Быстрый и плавный оверлей на DirectX 11.

Скачивание доступно в личном кабинете после авторизации.', true, now() - interval '1 day')
on conflict do nothing;

insert into public.settings (key, value)
values
('app_version', 'v266.1.0'),
('download_url', 'https://github.com/flishka/Silence/releases'),
('discord_url', 'https://discord.gg/silence-external'),
('telegram_url', 'https://t.me/silence_dev'),
('registration_enabled', 'true'),
('download_enabled', 'true')
on conflict do nothing;
